### ISSUE TITLE
Insecticide resistance

### ISSUE THREAD

**Issue by cclarkson** [malariagen/ag1000g-phase2-data-paper#127]

**Comment by alimanfoo** [comment]
I spoke with DK about this today and proposed an idea which he liked...

We do an analysis which is aimed towards the question, where should PBO nets be deployed. There aren't any published genetic markers of P450-based pyrethroid resistance, but the presence of a copy number amplification at either the cyp6p/aa locus or the cyp9k1 locus is a strong indicator, given everything we know about P450s in general and about these specific loci.

For each individual mosquito in the phase 2 cohort, we ascertain (1) does it carry any kdr alleles, (2) does it have any amplification spanning any gene in the cyp6p/aa cluster, and (3) does it have any amplification spanning cyp9k1. 

For each population, we then compute (1) the frequency of individuals carrying a kdr allele but no amplifications at cyp6p/aa or cyp9k1, (2) the frequency of individuals carrying an amplification at either cyp6p/aa or cyp9k1 but no kdr allele, (3) the frequency of individuals carrying a kdr allele AND an amplification at either cyp6p/aa or cyp9k1, and (4) the frequency of individuals carrying no kdr alleles and no amplifications at cyp6p/aa or cyp9k1.

We then make a map with a pie chart for each population, where there are four colours in each pie chart, one for each of the four frequency classes described in the paragraph above. The legend would be something like:

[colour 1] kdr
[colour 2] P450 amplification
[colour 3] kdr + P450 amplification
[colour 4] wild type

Obviously this could be made more complicated, and we could elaborate in supplementary. E.g., one might want to know frequencies of cyp6p/aa and cyp9k1 separately. One might also want to know frequencies of kdr F and S separately. But it becomes a bit difficult to visualise, as you have to consider lots of combinations. I.e., an individual might have kdr F + cyp6p/aa amplification, or kdr S + cyp9k1 amplification, or kdr F + kdr S + cyp6p/aa amplification + cyp9k1 amplification, or other combinations. It becomes hard to visualise, and the message (what's the overall frequency of P450 resistance, and therefore where should we put PBO nets) gets a little lost.

We could explore these options, and there are other ways these data could be visualised apart from a map, but I'd suggest the simple four class analysis on a map as a starting point.

When we write the text about this we obviously have to be careful not to over-simplify this or make any over-reaching inferences, but we can make the link clear. E.g., begin with something like (obviously with some editing)...

> An important question currently facing malaria vector control programmes concerns the procurement and deployment of "next-generation" LLINs which combine pyrethroid with a PBO synergist which counteracts metabolic resistance caused by cytochrome P450 genes. There are no published markers for P450-based pyrethroid resistance, however it is known that P450 resistance can be achieved via over-expression of P450 genes, which in turn can be achieved by copy number amplification of the relevant gene within the genome. We scanned the genomes of the mosquitoes in the phase 2 cohort for evidence of copy number variation, described in more detail in (Lucas et al. 2019). The CNV results are part of the phase 2 data resource. At two P450 loci in particular, the cyp6p/aa gene cluster and the cyp9k1 gene, we found a high frequency of copy number variation in multiple populations. These loci have also been found under recent positive selection in multiple populations (cite Ag1000G), and have been associated with pyrethroid resistance in other studies (refs). Thus it is reasonable to assume that the presence of CNVs at these loci is an adaptation to pyrethroids, although this remains to be tested. We then combined these data with data on nucleotide variation within the VGSC gene, which is the target for pyrethroids, to provide an estimate for the population frequencies of mosquitoes carrying some form of kdr target-site pyrethroid resistance, amplifications at either of the two P450 loci, or both (Figure @@N). We found that [tell the story of what the figure shows]...

**Comment by alimanfoo** [comment]
Btw happy to also discuss your ideas @cclarkson around looking at SNPs from Eric's paper. I still think it will be hard to relate to major operational questions, because so many markers will be missing. But if you have an idea and feel strongly then very happy to talk it through some more.
