### ISSUE TITLE
Variant calling methods

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#17]

**Comment by hardingnj** [comment]
For reference from paper 1:

> Sequence reads were aligned to the AgamP3 reference genome31 using bwa32 and SNPs were discovered using GATK following best practice recommendations33,34 (Supplementary Information 3.1–3.2). After sample quality control, we analysed data on 765 wild-caught specimens and a further 80 specimens comprising parents and progeny from the four laboratory crosses (Supplementary Information 3.3). The alignments were also used to identify genome regions accessible to SNP calling, where short reads could be uniquely mapped and there was minimal evidence for structural variation (Supplementary Information 3.4). Mendelian errors in the crosses were used to guide the design of filters to remove poor-quality variant calls (Supplementary Information 3.5). We performed capillary sequencing of five genes in 58 individual mosquitoes to provide an estimate for the SNP false discovery rate, sensitivity and genotyping accuracy (Supplementary Information 3.6). We also performed genotyping by primer-extension mass spectrometry using the Sequenom MassARRAY platform at 158 SNPs in 229 individual mosquitoes to provide a second estimate for genotyping accuracy (Supplementary Information 3.7).
