### ISSUE TITLE
CNV statistics

### ISSUE THREAD

**Issue by cclarkson** [malariagen/ag1000g-phase2-data-paper#190]
**@alimanfoo comments from a merged PR**

@EricRLucas could you also give me some stats on CNVs prior to filtering for 5% population allele frequency? I would be interested to know:

    How many CNVs in total (any frequency)?
    How many singletons (CNVs present only in a single individual)?
    How many non-singletons (CNVs present in at least two individuals)?
    Considering all CNVs (any frequency):
        How many distinct genes do they overlap?
        How many distinct genome positions do they overlap? (I.e., how many base pairs are overlapped by at least one CNV)?

These would be nice summary statistics, relevant to this paper as we are describing the genome variation resource, and also not a duplication of stuff reported in your CNV paper.

**Comment by cclarkson** [comment]
**@EricRLucas' repy via email**

Among the 1115 samples that passed filtering for variance, we found a
total of 31335 CNVs. 7086 of these were found in more than one sample,
and 1557 passed population-level frequency filtering.

Out of 10939 eligible genes, 4059 were found in at least one of the
31335 CNVs.
Out of 10939 eligible genes, 971 were found in at least one of the 7086
non-singleton CNVs.
Out of 10939 eligible genes, 267 were found in at least one of the 1557
CNVs that passed frequency filtering.

Out of 10939 eligible genes, 7190 were overlapped by at least one of the
31335 CNVs.
Out of 10939 eligible genes, 2429 were overlapped by at least one of the
7086 non-singleton CNVs.
Out of 10939 eligible genes, 645 were overlapped by at least one of the
1557 CNVs that passed frequency filtering.

Overall, there were 595154 300bp windows left after filtering.
229300 (38.5%) of filtered windows were covered by at least one CNV.
60490 (10.2%) of filtered windows were covered by at least one
non-singleton CNV.
14925 (2.5%) of filtered windows were covered by at least one frequency
filter-passing CNV.

The number of bp covered by CNVs can be calculated by multiplying the
above values by 300:
Overall, there were 178546200 bp left after filtering.
68790000 of these were covered by at least one CNV.
18147000 of these were covered by at least one non-singleton CNV.
4477500 of these were covered by at least one frequency filter-passing CNV.

**Comment by alimanfoo** [comment]
Perfect, thanks Eric!

**Comment by cclarkson** [comment]
The required stats have all been added to paper.
