### ISSUE TITLE
Genome accessibility results text

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#22]

**Comment by alimanfoo** [comment]
Could include some breakdown and comparison of accessibility by species.

**Comment by cclarkson** [comment]
we analysed genome to contruct map...coverage/map...overall we define whole genome %/exome%

> could look at finer grained features.
> break down by population/species - re-run analyses separately for species 
> we feel we *can* do this for phase 2 (gam/col), not possible for phase 3.

-- why are we talking about accessibility, why is is important, do we leave some of this out the paper but have it in hand for reviewers?

**Comment by cclarkson** [comment]
Currently this has been resolved by a sentence or two in the first results paragraph. Closing this now but could be revisited for finer grained analysis later.
