### ISSUE TITLE
Genome accessibility

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#24]
All content related to genome accessibility.

**Comment by cclarkson** [comment]
All 11 "good" crosses were used in the ME analyses:

crosses = (
    ('18-5', (0, 1)), 
# exclude as no parents?
#    ('22-1', (0, 1)),
    ('29-2', (0, 1)), 
    ('36-9', (0, 1)), 
# exclude as contaminated father
#    ('37-3', (0, 1))
    ('42-4', (0, 1)), 
    ('45-1', (1, 2)), 
    ('46-9', (0, 1)), 
    ('47-6', (0, 1)), 
    ('61-3', (0, 1)), 
    ('73-2', (1, 2)), 
    ('78-2', (0, 1)), 
    ('80-2', (1, 2)), 
)

**Comment by cclarkson** [comment]
Closing this, can re-open if there is interest in accessibility artwork.
