### ISSUE TITLE
Phasing artwork: update phase 1 plots with new crosses.

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#29]

**Comment by hardingnj** [comment]
I'm trying to make some headway on this today. 

- plot showing mendelian error rates before and after filtering
- phasing expected distance between switch errors across genome
- phasing switch error rates across genome
- rough plot of inferred recombination rate across genome

**Comment by alimanfoo** [comment]
Thanks Nick. 

> * plot showing mendelian error rates before and after filtering

FWIW I don't think we need a plot of Mendelian error rates before and after filtering, I think we could just state some numbers as we did in the phase 1 paper.

> * phasing expected distance between switch errors across genome
> * phasing switch error rates across genome

Are these the same as the two plots we included in the phase 1 paper?

> * rough plot of inferred recombination rate across genome

FWIW not sure this is needed? I wouldn't include a plot of recombination rate unless we are actually estimating recombination rate, could be confusing for reviewers.

Happy to discuss.

**Comment by hardingnj** [comment]
> FWIW I don't think we need a plot of Mendelian error rates before and after filtering, I think we could just state some numbers as we did in the phase 1 paper.

Great- no plots, just numbers!

> Are these the same as the two plots we included in the phase 1 paper?

Yes, just with more data this time around. The extra 7 crosses.

> FWIW not sure this is needed? I wouldn't include a plot of recombination rate unless we are actually estimating recombination rate, could be confusing for reviewers.

No problem- although I thought we did talk about producing one based on the recombinations observed in the progeny?

**Comment by hardingnj** [comment]
> * phasing expected distance between switch errors across genome
> * phasing switch error rates across genome

From the above- I need to work on these 2 things.
