### ISSUE TITLE
Genetic diversity within populations results text

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/ag1000g-phase2-data-paper#50]
**results text**

- [x] pi
- [x] tajD
- [x] ROH
- [x] IBD

**Comment by cclarkson** [comment]
coastal/inland coluzzii - different demography
Gambia/Guinea Bissau - similar demography

**Comment by cclarkson** [comment]
@hardingnj - The results section just needs a few sentences about your identity by descent figure and maybe a sentence or note in the discussion about how we can weave this in to the larger narrative.

Cheers
