### ISSUE TITLE
Phase2 latitude/longitude values

### ISSUE THREAD

**Issue by hardingnj** [malariagen/ag1000g-phase2-data-paper#7]
Hi @cclarkson,
Do we have latitude/longitude values for these samples anywhere? 

We had them in the meta for Phase 1, but not phase 2 it seems.

**Comment by cclarkson** [comment]
Hi @hardingnj 
Yes, I have the values for the new phase 2 samples in a planning document for the paper, I will share that below. Sonia has finished the Ag1000g meta data so we should have that soon, I'm also hoping that they are included in that.

                   
Cote d’Ivoire (CI): Tiassalé (5.89839N, -4.82293W) is located in the evergreen forest zone of southern Côte d’Ivoire. The primary agricultural activity is rice cultivation in irrigated fields. High malaria transmission occurs during the rainy seasons, between May and November. Samples were collected as larvae from irrigated rice fields by dipping between May and Septermber 2012. All larvae were reared to adults and females preserved over silica for DNA extraction using Qiagen DNAEasy kits.
                   
Equatorial Guinea (GQgam): Collections were performed during the rainy season in September, 2002 by overnight CDC light traps in Sacriba of Bioko island (3°42'00.0"N 8°42'00.0"E). Specimens were stored dry on silica gel and DNA was extracted using the Qiagen DNeasy Blood and Tissue Kit (Qiagen Science, Germantown, MD, USA). Specimens contributed from this site were An. gambiae females, genotype determined by two assays (Scott et al. 1993; Santolamazza et al. 2004). All specimens had the 2L+a/2L+a karyotype as determined by the molecular PCR diagnostics (White et al. 2007). These mosquitoes represent a population that inhabited Bioko Island before a comprehensive malaria control intervention initiated in February 2004 (Sharp et al. 2007). After the intervention An. gambiae was declining, and more recently almost only An. coluzzii can be found (Overgaard et al. 2012).

France (FRgam): Samples were collected as larvae during March-April 2011 in temporary pools by dipping, in Bouyouni (12°44'16,128"S, 45°08'30,104"E), M'Tsamboro Forest Reserve (12°42'09,755"S, 45°04'51,927"E), Combani (12°46'43,333"S, 45°08' 34,488"E), Mtsanga Charifou (12°59'26,382"S, 45°09'20,422"E), Karihani Lake forest reserve (12°47'47,49"S, 45°07'18,20"E), and Sada (12°51'07,730"S, 45°06'14,006"E) in Mayotte island. Larvae were stored in 80% ethanol and genomic DNA was extracted using the Qiagen DNeasy Blood and Tissue Kit (Qiagen Science, Germantown, MD, USA). All specimens contributed to Ag1000G phase 2 were An. gambiae (Santolamazza et al. 2004) with the standard 2L+a/2L+a or inverted 2La/2La karyotype as determined by the molecular PCR diagnostics (White et al. 2007). The samples were identified as males or females by the sequencing read coverage of the X chromosome using LookSeq (Manske and Kwiatkowski, 2009).

The Gambia (GM)                   
Indoor resting female mosquitoes were collected by pyrethrum spray catch (PSC) from four hamlets around Njabakunda (13°33’N, 15°54’W), North Bank Region, The Gambia between August and October 2011. The four hamlets were Maria Samba Nyado, Sare Illo Buya, Kerr Birom Kardo, and Kerr Sama Kuma; all are within 1 km of each other. This is an area of unusually high hybridization rates between Anopheles gambiae s.s. and An. coluzzii [1, 2]. Njabakunda village is approximately 30 km to the west of Farafenni town and 4 km away from the Gambia River. The vegetation is a mix of open savannah woodland and farmland.
                   
2.    Caputo, B., et al., Anopheles gambiae complex along The Gambia river, with particular reference to the molecular forms of An. gambiae s.s. Malaria Journal, 2008. 7.
3.    Nwakanma, D.C., et al., Breakdown in the process of incipient speciation in Anopheles gambiae. Genetics, 2013. 193(4).

                   
Ghana: Twifo Praso (05.608580N, 01.549260W) a peri-urban community located in semi-deciduous forest in the Central Region of Ghana. It is an extensive agricultural area characterised by small-scale (vegetable growing) and large-scale commercial farms such as oil palm and cocoa plantations. Mosquito samples were collected as larvae from puddles near farms between September and October, 2012. All larvae were reared to adults and females preserved over silica for DNA extraction using Qiagen DNAEasy kits. Madina (05.668490N, 00.219280W) is suburb of Accra within a coastal savanna zone of Ghana. It is an urban community characterised by myriad vegetable-growing areas. The vegetation consists of mainly grassland interspersed with dense short thickets often less than 5 m high with a few trees. Specimens were sampled from puddles near roadsides and farms between October and December 2012. All larvae were reared to adults and females preserved over silica for DNA extraction using Qiagen DNAEasy kits. Takoradi (04.912170N, 1.773970 W) is the capital city of Western Region of Ghana. It is an urban community located in the coastal savanna zone. Mosquito samples were collected from puddles near road construction and farms between August and September 2012. All larvae were reared to adults and females preserved over silica for DNA extraction using Qiagen DNAEasy kits. Koforidua (06.094490N, 0.260930W) is a capital city of Eastern Region of Ghana. It is located in semi-deciduous forest. it is an urban community characterized by numerous small-scale vegetable farms. Samples were collected from puddles near road construction and farms between August and September 2012. Mosquito samples were collected from gutters and puddles near roadsides between November and December 2012. All larvae were reared to adults and females preserved over silica for DNA extraction using Qiagen DNAEasy kits.

Guinea-Bissau: mosquitoes were collected in October 2010 using indoor CDC light traps, in the village of Safim (11º57'24.8''N, 15º38'57.2'' W), ca. 11 km north of Bissau city, the capital of the country. Malaria is hyperendemic in the region (Arez et al., 2003) and transmitted by members of the Anopheles gambiae complex (Vicente et al., 2017). Anopheles arabiensis, An. melas, A. coluzzii and A. gambiae, as well as hybrids between the latter two species, are known to occur in the region (Gordicho et al., 2014; Vicente et al., 2017). Mosquitoes were preserved individually on 0.5ml micro-tubes filled with silica gel and cotton. DNA extraction was performed by a phenol-chloroform protocol (Donnelly et al., 1999).

**Comment by hardingnj** [comment]
Thanks!

**Comment by alimanfoo** [comment]
Just to say, I spoke to @sclaugoncalves yesterday about sample metadata, she will provide us shortly with a manifest of all Ag1000G phase 3 samples, but location fields will not be complete. We should then work with her to fill out the location and other fields with her. 

xref https://github.com/wtsi-team112/vector-ops/issues/52
