### ISSUE TITLE
BUG in haplotypes file needs fixing before we can proceed

### ISSUE THREAD

**Issue by hardingnj** [malariagen/ag1000g-phase2-data-paper#96]
In `ag1000g.crosses.phase2.ar1.haplotypes.zip` in the release directory `/kwiat/vector/ag1000g/release/phase2.AR1/haplotypes/crosses/zarr2`

It seems to have been caused by me not understanding the difference between signed and unsigned ints [here](https://github.com/malariagen/ag1000g/blob/130de668449c32ca8fb89795ca7ac180573e058f/pipelines/phase2/phasing/phase-parents-progeny/Snakefile#L180)

I'll fix, and rerun the pipeline- then the fixed haplotype file will need copying to the release directory on the cluster and then the FTP. Apologies!

This blocks #30

**Comment by alimanfoo** [comment]
Thanks Nick, sounds good. Do you have access to the FTP directory? If not, @cclarkson may be able to copy there.
